# Generated by Django 2.2.4 on 2019-09-02 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officeaccounts', '0004_auto_20190902_1826'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
